In [11]:
#section 1
import numpy as np
import math

a = 1 / math.sqrt(2)
b = 1 / math.sqrt(2)

v = np.array([a, b])
print("Vector v:", v)

norm_check = a**2 + b**2
print("a^2 + b^2 =", norm_check)

if math.isclose(norm_check, 1.0):
    print("The vector is normalized")
else:
    print("The vector is NOT normalized")

length = np.linalg.norm(v)
print("Length of vector:", length)


#section 2
import numpy as np

n = int(input("Enter dimension of vector: "))
A = np.array(list(map(float, input("Enter elements of vector A: ").split())))

def is_normalized(v):
    return np.isclose(np.linalg.norm(v), 1)

print("Is vector A normalized?", is_normalized(A))

B = np.array(list(map(float, input("Enter elements of vector B: ").split())))

def dot_cross(A, B):
    dot = np.dot(A, B)
    cross = np.cross(A, B) if len(A) == 3 else "Cross product defined only for 3D vectors"
    return dot, cross

dot, cross = dot_cross(A, B)
print("Dot Product:", dot)
print("Cross Product:", cross)

def unit_vector(v):
    return v / np.linalg.norm(v)

print("Unit vector of A:", unit_vector(A))


#section 3
import numpy as np

r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))

matrix = []
for i in range(r):
    row = list(map(float, input().split()))
    matrix.append(row)

M = np.array(matrix)
print("Matrix:\n", M)

print("Transpose:\n", M.T)

if r == c:
    print("Determinant:", np.linalg.det(M))
else:
    print("Determinant not defined for non-square matrix")

print("Rank:", np.linalg.matrix_rank(M))

if r == c:
    print("Trace:", np.trace(M))
else:
    print("Trace not defined for non-square matrix")

if r == c:
    eigvals, eigvecs = np.linalg.eig(M)
    print("Eigenvalues:", eigvals)
    print("Eigenvectors:\n", eigvecs)

if r == c and np.linalg.det(M) != 0:
    print("Inverse:\n", np.linalg.inv(M))
else:
    print("Inverse does not exist")

import cmath

#section 4

z = complex(input("Enter a complex number (e.g., 3+4j): "))
print("Complex number:", z)

print("Conjugate:", z.conjugate())

z2 = complex(input("Enter another complex number: "))

print("Addition:", z + z2)
print("Subtraction:", z - z2)
print("Multiplication:", z * z2)
print("Division:", z / z2)

print("Real part (x-axis):", z.real)
print("Imaginary part (y-axis):", z.imag)

print("Magnitude:", abs(z))


Vector v: [0.70710678 0.70710678]
a^2 + b^2 = 0.9999999999999998
The vector is normalized
Length of vector: 0.9999999999999999
Enter dimension of vector: 3
Enter elements of vector A: 1 0 0
Is vector A normalized? True
Enter elements of vector B: 0 1 0
Dot Product: 0.0
Cross Product: [0. 0. 1.]
Unit vector of A: [1. 0. 0.]
Enter number of rows: 2
Enter number of columns: 2
1 2
3 4
Matrix:
 [[1. 2.]
 [3. 4.]]
Transpose:
 [[1. 3.]
 [2. 4.]]
Determinant: -2.0000000000000004
Rank: 2
Trace: 5.0
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Enter a complex number (e.g., 3+4j): 3+4j
Complex number: (3+4j)
Conjugate: (3-4j)
Enter another complex number: 1+2j
Addition: (4+6j)
Subtraction: (2+2j)
Multiplication: (-5+10j)
Division: (2.2-0.4j)
Real part (x-axis): 3.0
Imaginary part (y-axis): 4.0
Magnitude: 5.0
